In [ ]:
import numpy as np
import pandas as pd

In [ ]:
restaurants = pd.read_excel('dataset.xlsx', sheet_name='Restaurants')
customers = pd.read_excel('dataset.xlsx', sheet_name='Customers')
orders = pd.read_excel('dataset.xlsx', sheet_name='Orders')

# Restaurants

In [ ]:
restaurants.head()

,RestaurantID,address,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,1,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,2,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,3,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,4,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,5,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

In [ ]:
restaurants.shape

(56250, 14)

In [ ]:
restaurants.drop('address', axis=1, inplace=True)

In [ ]:
# restaurants name column - cleaning
restaurants = restaurants[restaurants['name'].str.split().str.len() <= 5]
restaurants = restaurants[~restaurants['name'].str.contains(r'\d', regex=True, na=False)]
restaurants['name'] = (restaurants['name'].str.strip().str.replace(r'[^a-zA-Z\s]', '', regex=True))
restaurants = restaurants[restaurants['name'].str.len() > 3]

In [ ]:
words = ['food', 'service', 'taste', 'ambience', 'experience', 'amazing', 'good', 'great', 'must', 'try', 'recommended', 'delicious',
'rating', 'rated', 'review', 'cake', 'Alley', 'Recommend', 'Goa 0 Km', 'Bohra', 'Foreign', 'Bati', 'Betroot', 'Boti Kabab', 'Butter naan'
'fish', 'Dal', 'fritters', 'balls', 'sausages', 'tomato', 'omllete', 'Cheese burst pizza', 'Dosas', 'soup', 'nice', 'fish', 'bread',
'I may not visit again', 'apple', 'karimeen fry', 'Jal jeerra', 'Kadi', 'Lachha Paratha', 'Fried Hanbanero Chicken burger', 'Meals',
'Luchi Cholar Day', 'Italian on Tuesdays', 'Lamb Racks', 'Minted Arancini', 'Mixed veg subzi', '√É', 'Chop', 'Fry', 'prepared', 'supreme',
'duplex', 'gobi', 'peri', 'stay', 'mushrooms', 'thai', 'tandoori', 'drinks', 'tikka', 'sweet', 'paneer', 'starters', 'fungi', 'go',
'say', 'and', 'awesome', 'style', 'potato', 'me', 'fun', 'but', 'cheap', 'chicken', 'colorful', 'crispy', 'quick', 'fries', 'thank',
'fresh', 'you', 'little', 'it', 'wheat', 'money', 'veggies', 'ice-cream', 'quantity', 'totally', 'though', 'tried', 'the', 'thanks',
'well', 'left', 'staffs', 'spinach', 'no', 'sabzi', 'salads', 'screening', 'sizzlers', 'roti', 'chilli', 'place', 'work', 'of', 'not',
'bowl', 'advice', 'mutton', 'music', 'mushroom', 'main', 'it', 'is', 'check', 'chic', 'cocktail', 'leaves', 'bar', 'Rubs', 'compact',
'fried', 'staff', 'busy', 'ghee', 'guava', 'chocolate', 'people', 'had', 'continental', 'how', 'however', 'lights', 'was', 'beef',
'tea', 'lemon', 'chips', 'much', 'were', 'olives', 'rice', 'cabbage', 'pastas']

restaurants = restaurants[~restaurants['name'].str.contains('|'.join(words), case=False, na=False)]

In [ ]:
# online_order column and book_table column
restaurants = restaurants[(restaurants['online_order'] == 'Yes') | (restaurants['online_order'] == 'No')]
restaurants = restaurants[(restaurants['book_table'] == 'Yes') | (restaurants['book_table'] == 'No')]

In [ ]:
# rate column
restaurants['rate'] = restaurants['rate'].str.split('/').str.get(0)

In [ ]:
restaurants['rate'] = restaurants['rate'].replace(['NEW', '-'], 0)
restaurants['rate'] = pd.to_numeric(restaurants['rate'].str.strip())
restaurants['rate'] = restaurants['rate'].fillna(0)

In [ ]:
# location column
restaurants = restaurants.dropna(subset=['location'])

In [ ]:
# approx_cost(for two people) column
restaurants['approx_cost(for two people)'] = restaurants['approx_cost(for two people)'].fillna(restaurants['approx_cost(for two people)'].mean())

/tmp/ipykernel_954/3980324571.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  restaurants['approx_cost(for two people)'] = restaurants['approx_cost(for two people)'].fillna(restaurants['approx_cost(for two people)'].mean())

In [ ]:
# rest_type column
restaurants['rest_type'] = restaurants['rest_type'].str.split(',').str[0].str.strip()
restaurants['rest_type'] = restaurants['rest_type'].fillna('Unknown')

In [ ]:
# listed_in(type) column
restaurants['listed_in(type)'] = restaurants['listed_in(type)'].fillna('Unknown')

In [ ]:
# dish_liked column
restaurants['dish_liked'] = restaurants['dish_liked'].str.split(',').str.get(0)
restaurants['dish_liked'] = restaurants['dish_liked'].fillna('Unknown')

In [ ]:
# cuisines
restaurants['cuisines'] = restaurants['cuisines'].str.split(',').str.get(0)
restaurants['cuisines'] = restaurants['cuisines'].fillna('Unknown')

In [ ]:
# listed_in(city)
restaurants['listed_in(city)'] = restaurants['listed_in(city)'].fillna(restaurants['location'])

In [ ]:
def clean_location(x):
    x = str(x)

    if "Whitefield" in x:
        return "Whitefield"

    elif "Koramangala" in x:
        return "Koramangala"

    else:
        return x

In [ ]:
restaurants['listed_in(city)'] = restaurants['listed_in(city)'].apply(clean_location)

In [ ]:
# votes
restaurants['votes'] = restaurants['votes'].astype('float64')

In [ ]:
restaurants.rename(columns={
    'RestaurantID': 'restaurant_id',
    'name': 'restaurant_name',
    'online_order': 'online_order',
    'book_table': 'table_booking',
    'rate': 'rating',
    'votes': 'total_votes',
    'location': 'location',
    'rest_type': 'restaurant_type',
    'dish_liked': 'dishes_liked',
    'cuisines': 'cuisines',
    'approx_cost(for two people)': 'cost_for_two',
    'listed_in(type)': 'service_type',
    'listed_in(city)': 'city_category'
}, inplace=True)

In [ ]:
restaurants.to_csv('restaurants.csv', index=False)

# Customers

In [ ]:
customers.head()

   CustomerID CustomerName                   City SignupDate CustomerType
0           1   Customer_1         Residency Road 2023-02-10    Returning
1           2   Customer_2  Koramangala 7th Block 2023-04-18    Returning
2           3   Customer_3        Electronic City 2022-11-29          New
3           4   Customer_4                    BTM 2023-03-11    Returning
4           5   Customer_5  Koramangala 8th Block 2023-02-22          New

In [ ]:
customers.shape

(17498, 5)

In [ ]:
city = ["Residency Road", "Koramangala 7th Block", "Electronic City", "BTM", "Koramangala 8th Block",
        "Koramangala 4th Block", "Malleshwaram", "Banashankari", "Koramangala 5th Block", "Brigade Road",
        "MG Road", "Bellandur", "New BEL Road", "Marathahalli", "Kammanahalli", "Race Course Road", "JP Nagar",
        "Lavelle Road", "Basavanagudi", "Whitefield", "Shanti Nagar", "HSR", "Ejipura", "Koramangala 2nd Block",
        "Jeevan Bhima Nagar","Commercial Street", "Koramangala 6th Block", "Kalyan Nagar", "Indiranagar",
        "Koramangala 1st Block", "Ulsoor", "Seshadripuram", "Bannerghatta Road", "Jayanagar", "City Market",
        "Nagawara", "Rajajinagar", "Sarjapur Road", "Banaswadi", "Basaveshwara Nagar", "Hennur", "South Bangalore",
        "Brookefield","Bommanahalli", "Wilson Garden", "CV Raman Nagar", "Shivajinagar", "Church Street", "Ulsoor",
        "Vasanth Nagar", "Cunningham Road", "Domlur", "Frazer Town", "Old Airport Road", "Richmond Road", "St. Marks Road"]

In [ ]:
customers = customers[customers['City'].isin(city)]

In [ ]:
customers.rename(columns={
    'CustomerID': 'customer_id',
    'CustomerName': 'customer_name',
    'City': 'city',
    'SignupDate': 'signup_date',
    'CustomerType': 'customer_type'
}, inplace=True)

In [ ]:
customers.to_csv('customers.csv', index=False)

# Orders

In [ ]:
orders.head()

,OrderID,RestaurantID,CustomerID,OrderDate,OrderValue,DeliveryTimeMins,OrderStatus,Quantity
0,1,32876,15443,2025-05-21,719,53,Delivered,4
1,2,3567,821,2023-04-08,1411,46,Delivered,1
2,3,49893,14072,2025-06-30,605,36,Delivered,1
3,4,43691,8141,2023-03-19,1118,20,Delivered,2
4,5,42789,1402,2024-07-11,271,30,Delivered,3

In [ ]:
orders.shape

(200000, 8)

In [ ]:
orders.columns

Index(['OrderID', 'RestaurantID', 'CustomerID', 'OrderDate', 'OrderValue',
       'DeliveryTimeMins', 'OrderStatus', 'Quantity'],
      dtype='object')

In [ ]:
orders = orders[
    orders['CustomerID'].isin(customers['customer_id']) &
    orders['RestaurantID'].isin(restaurants['restaurant_id'])
]

In [ ]:
orders.rename(columns={
    'OrderID': 'order_id',
    'RestaurantID': 'restaurant_id',
    'CustomerID': 'customer_id',
    'OrderDate': 'order_date',
    'OrderValue': 'order_value',
    'DeliveryTimeMins': 'delivery_time_mins',
    'OrderStatus': 'order_status',
    'Quantity': 'quantity'
}, inplace=True)

In [ ]:
orders.to_csv('orders.csv', index=False)